// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Linq;
using Elcometer.Core.Model;
using Foundation;
using UIKit;

namespace Elcometer.Demo.iOS
{
	public partial class BatchInfoViewController : UIViewController
	{
		public BatchInfoViewController (IntPtr handle) : base (handle)
		{
		}

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            string info = "";

            info += $"Batch: {Batch.Name}\n";
            info += $"Readings: {Batch.IncludedCount}\n";
            info += "\n";

            foreach (var reading in Batch.GetReadings().Select(x => x.Value).OrderBy(x => x.Id).ToList())
            {
                if (reading.IncludeInStats)
                {
                    string readings = "";

                    for (int i = 0; i < Batch.ColumnCount; i++)
                    {
                        if (!String.IsNullOrEmpty(readings))
                        {
                            readings += ", ";
                        }

                        readings += reading.ToDisplayStringWithUnit(i);
                    }

                    info += $"{reading.Id}: {readings}\n";
                }
            }

            BatchInfoTextView.Text = info;
            BatchInfoTextView.Editable = false;
        }

        public Batch Batch { get; set; }
	}
}
